### ISSUE TITLE
Annotation Function for the pseudocode list 

### ISSUE THREAD

**Issue by yiyuanli939** [andreasKroepelin/lovelace#23]
Is there a function in lovelace that can add annotation commonly used in algorithm like "// insert x to y"? If no, may I join in and try to find one?

**Comment by andreasKroepelin** [comment]
There was something like that in earlier versions but it felt a bit too opinionated. I think that people have widely varying preferences how comments should look in pseudo code, so just build your own. It's not too hard in Typst.
