### ISSUE TITLE
Add Annotations "//" in pseudocode-list

### ISSUE THREAD

**Issue by yiyuanli939** [andreasKroepelin/lovelace#24]
Hi, in my current usage of the lovelace package. It seems that there is no way to add annotations like "// mid point of A[p:r]" that is quite common in classical algorithm book like CLRS. Right now I can only use the clumsy / / with a empty space in it. Is there a problem for inplement annotations that can be seen in the output document? 

If you have an idea but do not have time, I'm also glad to try to find a way to update this package.

**Comment by andreasKroepelin** [comment]
Try using `#sym.slash.double`? You can of course define some abbreviation for that.
In my personal opinion, mixing C-syntax with pseudo code is a bit strange but of course you can do whatever you want, that's the idea of Lovelace :)

**Comment by andreasKroepelin** [comment]
And to be clear, if `//` doesn't work, that's a limitation of Typst. So I'll close this issue.
