### ISSUE TITLE
`#algorithm` makes code centered and missing horizontal lines.

### ISSUE THREAD

**Issue by RomeoV** [andreasKroepelin/lovelace#7]
First of all, thanks for this package, it looks great!

I'm trying to compile one of the examples. I have, in an otherwise empty document:

```
#import "@preview/lovelace:0.2.0": *
#algorithm(
  caption: [The Euclidean algorithm],
  pseudocode(
    no-number,
    [*input:* integers $a$ and $b$],
    no-number,
    [*output:* greatest common divisor of $a$ and $b$],
    [*while* $a != b$ *do*], ind,
      [*if* $a > b$ *then*], ind,
        $a <- a - b$, ded,
      [*else*], ind,
        $b <- b - a$, ded,
      [*end*], ded,
    [*end*],
    [*return* $a$]
  )
)
```

However, all the text is centered, and I am missing the horizontal lines that the examples had. Any ideas?

[
![screenshot_2024-05-26T01:55:14UTC](https://github.com/andreasKroepelin/lovelace/assets/8644490/f9bab5fc-895d-4eac-9ca3-d0b7341e84f5)
](url)

**Comment by andreasKroepelin** [comment]
From the readme:
> Note that such figures are only displayed correctly when you used the setup function mentioned above!

**Comment by RomeoV** [comment]
Oops, sorry for that! "Fixed".
